name: Build linux binary CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gcc-compiler:latest
    - name: Compile linux binary
      run: |
        docker run \
          -v "$(pwd)/bin/":/app/bin/ \
          gcc-compiler:latest \
          cmake . && make
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: bin/