name: Build linux binary CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create builder
      run: docker build --tag=builder:latest .

    - name: Build Web package
      run: docker run -v "$(pwd)"/build/bin:/src/build/bin builder:latest /src/scripts/build-web.sh
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: build/bin/

    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: /build/bin/*
        remote: ${{ secrets.SERVER_PATH }}
        host: ${{ secrets. SERVER_URL }}
        privateKey: ${{ secrets.SERVER_PRIVATE_SSH_KEY }}
        username: ${{ secrets.SERVER_USER }}

        